[package]
name = "quickwit-doc-mapper"
version = "0.3.1"
authors = ["Quickwit, Inc. <hello@quickwit.io>"]
edition = "2021"
license = "AGPL-3.0-or-later"                           # For a commercial, license, contact hello@quickwit.io
description = "Quickwit index configuration"
repository = "https://github.com/quickwit-oss/quickwit"
homepage = "https://quickwit.io/"
documentation = "https://quickwit.io/docs/"

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
dyn-clone = { workspace = true }
fnv = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
mockall = { workspace = true, optional = true }
once_cell = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
siphasher = { workspace = true }
tantivy = { workspace = true }
tantivy-query-grammar = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
time-fmt = "0.3.8"
ouroboros = "0.15.5"
tracing = { workspace = true }
typetag = { workspace = true }

quickwit-proto = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
criterion = { workspace = true }
matches = { workspace = true }

[features]
testsuite = []

[[bench]]
name = "doc_to_json_bench"
harness = false
