[workspace]
resolver = "2"
members = [
  "quickwit-actors",
  "quickwit-common",
  "quickwit-cli",
  "quickwit-cluster",
  "quickwit-config",
  "quickwit-core",
  "quickwit-doc-mapper",
  "quickwit-directories",
  "quickwit-metastore",
  "quickwit-proto",
  "quickwit-pushapi",
  "quickwit-search",
  "quickwit-serve",
  "quickwit-storage",
  "quickwit-telemetry",
  "quickwit-indexing",
]

[profile.dev]
debug = 0
