ignore = [
  "quickwit-proto/src/cluster.rs",
  "quickwit-proto/src/quickwit.rs",
  "quickwit-proto/src/quickwit_ingest_api.rs",
  "quickwit-proto/src/quickwit_metastore_api.rs",
]

comment_width = 120
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
normalize_comments = true
where_single_line = true
wrap_comments = true
