ignore = [
  "quickwit-proto/src/cluster.rs",
  "quickwit-proto/src/quickwit.rs",
  "quickwit-proto/src/quickwit_push_api.rs",
]

comment_width = 120
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
license_template_path = ".license_header.txt"
normalize_comments = true
where_single_line = true
wrap_comments = true
