[package]
name = "elastic-api-generator"
version = "0.1.0"
edition = "2021"

[workspace]
# This is just to make sure this project is not part
# of the quickwit workspace.
members = []

[dependencies]
quickwit_elastic_api_generation = { git = "https://github.com/quickwit-oss/elasticsearch-rs", rev = "dca3aba" }
once_cell = "1"
clap = "4"
anyhow = "1"
