apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: searcher
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quickwit
      service: searcher
  serviceName: searchers
  template:
    metadata:
      labels:
        app: quickwit
        service: searcher
    spec:
      containers:
        - name: quickwit
          image: quickwit/quickwit:edge
          imagePullPolicy: Always
          args: ["run", "--service", "searcher"]
          ports:
            - containerPort: 7280
              name: rest
            - containerPort: 7281
              name: grpc
            - containerPort: 7282
              protocol: UDP
              name: discovery
          volumeMounts:
            - name: config-volume
              mountPath: /quickwit/node.yaml
              subPath: node.yaml
            - name: qwdata-volume
              mountPath: /quickwit/qwdata
            - name: indexes-volume
              mountPath: /quickwit/indexes
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: QW_CONFIG
              value: node.yaml
            - name: QW_NODE_ID
              value: "$(POD_NAME)"
            - name: QW_PEER_SEEDS
              value: "discovery.$(NAMESPACE).svc.cluster.local"
            - name: QW_ADVERTISE_ADDRESS
              value: "$(POD_IP)"
          # readinessProbe:
          #   httpGet:
          #     path: /healthz/searcher/readyz
          #     port: rest
          # livenessProbe:
          #   httpGet:
          #     path: /healthz/searcher/livez
          #     port: rest
      volumes:
        - name: config-volume
          configMap:
            name: quickwit-config
        - name: qwdata-volume
          emptyDir: {}
        - name: indexes-volume
          persistentVolumeClaim:
            claimName: indexes-pv-claim
