[package]
name = 'quickwit-serve'
version = '0.1.0'
authors = ['Quickwit <hello@quickwit.io>']
edition = '2021'
license = "AGPL-3.0-or-later" # For a commercial, license, contact hello@quickwit.io
description = "Quickwit's search service"
repository = "https://github.com/quickwit-inc/quickwit"
homepage = "https://quickwit.io/"
documentation = "https://quickwit.io/docs/"

[dependencies]
anyhow = '1'
warp = '0.3'
hyper = { version = "0.14", features = ["stream", "server", "http1", "http2", "tcp", "client"] }
futures = "0.3"
futures-util = { version = "0.3.1", default-features = false }
tracing = '0.1'
quickwit-proto = {path="../quickwit-proto"}
serde_json = "1"
quickwit-config = {path="../quickwit-config"}
quickwit-storage = {path="../quickwit-storage"}
quickwit-common = {path="../quickwit-common"}
quickwit-metastore = {path="../quickwit-metastore"}
quickwit-telemetry = {path="../quickwit-telemetry"}
quickwit-directories = {path="../quickwit-directories"}
thiserror = "1"
tonic = "0.5.2"
async-trait = "0.1"
termcolor = "1"
bytes = "1"
tokio = { version = "1.7", features = [ "full" ] }
tokio-stream = "0.1.6"
opentelemetry = "0.16"
tracing-opentelemetry = "0.15"
prometheus = "0.13"
once_cell = '1'

[dev-dependencies]
mockall = "0.10"
assert-json-diff = "2.0.1"
tokio = { version = "1", features = ["full"] }
quickwit-storage = { version = "0.1.0", path = "../quickwit-storage", features=["testsuite"]}
quickwit-core = {path="../quickwit-core"}
quickwit-indexing= {path="../quickwit-indexing"}
quickwit-index-config = {path="../quickwit-index-config"}

[dependencies.quickwit-cluster]
path = '../quickwit-cluster'

[dependencies.quickwit-search]
path = '../quickwit-search'

[dependencies.serde]
version = '1.0'
features = ['derive']

[dependencies.serde_qs]
version = '0.8'
features = ['warp']
