[package]
name = 'quickwit-search'
version = '0.1.0'
authors = ['Paul Masurel <paul@quickwit.io>']
edition = '2018'

[dependencies]
anyhow = '1'
async-trait = "0.1"
base64 = '0.13'
futures = '0.3'
http = "0.2"
mockall = "0.9"
itertools = '0.10'
thiserror = "1"
tonic = '0.4.3'
tokio-stream = '0.1.6'
tracing = "0.1"

[dependencies.tantivy]
git = 'https://github.com/quickwit-inc/tantivy'
rev = 'c1d1d84'

[dependencies.quickwit-core]
path = '../quickwit-core'

[dependencies.quickwit-cluster]
path = '../quickwit-cluster'

[dependencies.quickwit-doc-mapping]
path = '../quickwit-doc-mapping'

[dependencies.tokio]
version = '1'
features = ['full']

[dependencies.tokio-util]
version = '0.6'
features = ['full']

[dependencies.quickwit-directories]
path = '../quickwit-directories'

[dependencies.quickwit-proto]
path = '../quickwit-proto'

[dependencies.quickwit-metastore]
path = '../quickwit-metastore'

[dependencies.quickwit-storage]
path = '../quickwit-storage'

[dev-dependencies]
serde_json = "1"
assert-json-diff = "2"
