[package]
name = "quickwit-metastore"
version = "0.1.0"
authors = ['Quickwit, Inc. <hello@quickwit.io>']
edition = "2018"
license = "AGPL-3.0-or-later" # For a commercial, license, contact hello@quickwit.io

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
quickwit-doc-mapping = { version = "0.1.0", path = "../quickwit-doc-mapping" }
quickwit-storage = { version = "0.1.0", path = "../quickwit-storage" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"

[dev-dependencies]
mockall = '0.9'
