version: "3.9" 
services:
  postgres: 
    image: postgres:13.1 
    environment: 
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
    ports: 
      - "127.0.0.1:5432:5432"
