[package]
name = 'quickwit-proto'
version = '0.1.0'
authors = ['Quickwit, inc <hello@quickwit.io>']
edition = '2018'
license = 'AGPL-3.0-or-later'  # For a commercial, license, contact hello@quickwit.io

[dependencies]
tonic = '0.4.3'
prost = '0.7'
serde_json = '1'

[dependencies.serde]
version = '1'
features = ['derive']

[build-dependencies]
tonic-build = '0.4.1'
prost-build = '*'
