[package]
name = 'quickwit-proto'
version = '0.1.0'
authors = ['Quickwit, inc <hello@quickwit.io>']
edition = '2018'
license = 'AGPL-3.0-or-later'  # For a commercial, license, contact hello@quickwit.io
description = "Quickwit's protos"
repository = "https://github.com/quickwit-inc/quickwit"
homepage = "https://quickwit.io/"
documentation = "https://quickwit.io/docs/"

[dependencies]
tonic = '0.5.2'
prost = { version = "0.8", default-features = false, features = ["prost-derive"] }
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
tonic-build = '0.5.2'
prost-build = '0.8.0'
