#
# Index config file for receiving logs in OpenTelemetry format.
# Link: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md
#

version: 0

index_id: otel-trace

doc_mapping:
  mode: lenient
  field_mappings:
    - name: trace_id
      type: text
      tokenizer: raw
    - name: trace_state
      type: text
      indexed: true # TODO: set to false
      stored: true
    - name: service_name
      type: text
      tokenizer: raw
    - name: span_id
      type: text
      tokenizer: raw
    - name: span_kind
      type: json
      tokenizer: raw
    - name: span_name
      type: text
      tokenizer: raw
    - name: span_start_timestamp_nanos
      type: datetime
      input_formats:
        - unix_timestamp
      fast: true
      precision: seconds
    - name: span_end_timestamp_nanos
      type: datetime
      input_formats:
        - unix_timestamp
      fast: true
      precision: seconds
    - name: span_attributes
      type: json
      tokenizer: raw
    - name: span_dropped_attributes_count
      type: u64
      indexed: false
    - name: span_dropped_events_count
      type: u64
      indexed: false
    - name: span_dropped_links_count
      type: u64
      indexed: false
    - name: span_status
      type: json
      indexed: false
    - name: parent_span_id
      type: text
      tokenizer: raw

indexing_settings:
  commit_timeout_secs: 30
  timestamp_field: span_start_timestamp_nanos

search_settings:
  default_search_fields: []
