[package]
name = "quickwit-core"
version = "0.1.0"
authors = ["Quickwit, Inc. <hello@quickwit.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
quickwit-doc-mapping = { version = "0.1.0", path = "../quickwit-doc-mapping" }
quickwit-metastore = { version = "0.1.0", path = "../quickwit-metastore" }
