[package]
name = "quickwit-core"
version = "0.1.0"
authors = ["Quickwit, Inc. <hello@quickwit.io>"]
edition = "2018"
license = "AGPL-3.0-or-later" # For a commercial, license, contact hello@quickwit.io

[dependencies]
anyhow = "1.0"
quickwit-doc-mapping = { version = "0.1.0", path = "../quickwit-doc-mapping" }
quickwit-metastore = { version = "0.1.0", path = "../quickwit-metastore" }
