[package]
name = "quickwit-indexing"
version = "0.5.0"
authors = ["Quickwit, Inc. <hello@quickwit.io>"]
edition = "2021"
license = "AGPL-3.0-or-later"                           # For a commercial, license, contact hello@quickwit.io
description = "Quickwit indexing"
repository = "https://github.com/quickwit-oss/quickwit"
homepage = "https://quickwit.io/"
documentation = "https://quickwit.io/docs/"

[dependencies]
anyhow = { workspace = true }
arc-swap = { workspace = true }
async-trait = { workspace = true }
backoff = { workspace = true, optional = true }
byte-unit = { workspace = true }
bytes = { workspace = true }
chitchat = { workspace = true }
fail = { workspace = true }
flume = { workspace = true }
fnv = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
libz-sys = { workspace = true, optional = true }
once_cell = { workspace = true }
oneshot = { workspace = true }
openssl = { workspace = true, optional = true }
pulsar = { workspace = true, optional = true }
rdkafka = { workspace = true, optional = true }
rusoto_core = { workspace = true, optional = true }
rusoto_kinesis = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
tantivy = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
ulid = { workspace = true }
utoipa = { workspace = true }
value = { workspace = true }
vrl = { workspace = true }
vrl-stdlib = { workspace = true }

quickwit-actors = { workspace = true }
quickwit-aws = { workspace = true }
quickwit-cluster = { workspace = true }
quickwit-common = { workspace = true }
quickwit-config = { workspace = true }
quickwit-directories = { workspace = true }
quickwit-doc-mapper = { workspace = true }
quickwit-grpc-clients = { workspace = true }
quickwit-ingest = { workspace = true }
quickwit-metastore = { workspace = true }
quickwit-proto = { workspace = true }
quickwit-storage = { workspace = true }

[features]
kafka = ["rdkafka", "backoff"]
kafka-broker-tests = []
vendored-kafka = ["kafka", "libz-sys/static", "openssl/vendored", "rdkafka/gssapi-vendored"]
vendored-kafka-macos = ["kafka", "libz-sys/static", "openssl/vendored"]
kinesis = ["rusoto_core", "rusoto_kinesis", "quickwit-aws/kinesis"]
kinesis-localstack-tests = []
pulsar = ["dep:pulsar"]
pulsar-broker-tests = []
testsuite = ["quickwit-actors/testsuite"]

[dev-dependencies]
bytes = { workspace = true }
criterion = { workspace = true, features = ["async_tokio"] }
mockall = { workspace = true }
proptest = { workspace = true }
rand = { workspace = true }
tempfile = { workspace = true }
reqwest = { workspace = true }

quickwit-actors = { workspace = true, features = ["testsuite"] }
quickwit-cluster = { workspace = true, features = ["testsuite"] }
quickwit-doc-mapper = { workspace = true, features = ["testsuite"] }
quickwit-common = { workspace = true, features = ["testsuite"] }
quickwit-config = { workspace = true, features = ["testsuite"] }
quickwit-metastore = { workspace = true, features = ["testsuite"] }
quickwit-storage = { workspace = true, features = ["testsuite"] }

[[test]]
name = "failpoints"
path = "failpoints/mod.rs"
required-features = ["fail/failpoints"]

[[bench]]
name = "doc_process_vrl_bench"
harness = false
