name: Publish Docker image to Docker Hub (nightly)

on:
  push:
    branches:
      - "main"
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - "quickwit-*/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: quickwit/quickwit-nightly
          labels: |
            org.opencontainers.image.title=Quickwit
            maintainer=Quickwit, Inc. <hello@quickwit.io>
            org.opencontainers.image.vendor=Quickwit, Inc.
            org.opencontainers.image.licenses=AGPL-3.0
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
