name: Build and publish Docker images

on:
  push:
    branches:
      - main
    tags:
      - airmail
      - happy-plazza
      - qw*
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            quickwit/quickwit
          tags: |
            type=edge,branch=main
            type=edge,branch=main,suffix=-bullseye
            type=semver,pattern={{version}}
            type=semver,pattern={{version}},suffix=-bullseye
            type=ref,event=tag
          labels: |
            org.opencontainers.image.title=Quickwit
            maintainer=Quickwit, Inc. <hello@quickwit.io>
            org.opencontainers.image.vendor=Quickwit, Inc.
            org.opencontainers.image.licenses=AGPL-3.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Retrieve commit date, hash, and tags
        run: |
          echo "QW_COMMIT_DATE=$(TZ=UTC0 git log -1 --format=%cd --date=format-local:%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV
          echo "QW_COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "QW_COMMIT_TAGS=$(git tag --points-at HEAD | tr '\n' ',')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: |
            QW_COMMIT_DATE=${{ env.QW_COMMIT_DATE }}
            QW_COMMIT_HASH=${{ env.QW_COMMIT_HASH }}
            QW_COMMIT_TAGS=${{ env.QW_COMMIT_TAGS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
