[workspace]
resolver = "2"
members = [
  "quickwit-actors",
  "quickwit-aws",
  "quickwit-cli",
  "quickwit-cluster",
  "quickwit-common",
  "quickwit-config",
  "quickwit-control-plane",
  "quickwit-core",
  "quickwit-directories",
  "quickwit-doc-mapper",
  "quickwit-grpc-clients",
  "quickwit-indexing",
  "quickwit-ingest-api",
  "quickwit-jaeger",
  "quickwit-janitor",
  "quickwit-metastore",
  "quickwit-metastore-utils",
  "quickwit-opentelemetry",
  "quickwit-proto",
  "quickwit-rest-client",
  "quickwit-search",
  "quickwit-serve",
  "quickwit-storage",
  "quickwit-telemetry",
]

[profile.dev]
debug = 0

[workspace.dependencies]
anyhow = "1"
arc-swap = "1.6"
assert-json-diff = "2"
async-speed-limit = "0.4"
async-trait = "0.1"
atty = "0.2"
azure_core = "0.5.0"
azure_storage = "0.6.0"
azure_storage_blobs = "0.6.0"
backoff = { version = "0.4", features = ["tokio"] }
base64 = "0.21"
byte-unit = { version = "4", default-features = false, features = ["serde"] }
bytes = "1"
chitchat = { git = "https://github.com/quickwit-oss/chitchat", rev = "cd568ba" }
chrono = "0.4.23"
clap = { version = "=3.1", features = ["env"] }
colored = "2.0.0"
console-subscriber = "0.1.8"
criterion = { version = "0.4", features = ["async_tokio"] }
cron = "0.11.0"
dialoguer = "0.10.3"
dotenv = "0.15"
dyn-clone = "1.0.10"
ec2_instance_metadata = "0.3"
enum-iterator = "1.2"
env_logger = "0.9"
fail = "0.5"
flume = "0.10"
fnv = "1"
futures = "0.3"
futures-util = { version = "0.3.25", default-features = false }
home = "0.5.4"
hostname = "0.3"
http = "0.2"
humansize = "2.1.3"
humantime = "2.1.0"
hyper = { version = "0.14", features = [
  "stream",
  "server",
  "http1",
  "http2",
  "tcp",
  "client",
] }
hyper-rustls = "0.23"
indexmap = { version = "1.9.2", features = ["serde"] }
itertools = "0.10.5"
json_comments = "0.2"
libz-sys = "1.1.8"
lru = "0.9"
matches = "0.1.9"
md5 = "0.7"
mime_guess = "2.0.4"
mockall = "0.11"
mrecordlog = { git = "https://github.com/quickwit-oss/mrecordlog", rev="8b0e0cfacbbbfc9a544011b01380d689a6c7a3ae" }
new_string_template = "1.4.0"
num_cpus = "1"
nom = "7.1.3"
once_cell = "1"
oneshot = "0.1.5"
openssl = { version = "0.10.45", default-features = false }
openssl-probe = "0.1.5"
opentelemetry = { version = "0.18", features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "0.17", features = ["rt-tokio"] }
opentelemetry-otlp = "0.11.0"
pin-project-lite = "0.2.9"
pnet = { version = "0.31.0", features = ["std"] }
predicates = "2"
prometheus = { version = "0.13", features = ["process"] }
proptest = "1"
prost = { version = "0.11.6", default-features = false, features = [
  "prost-derive",
] }
prost-build = "0.11.6"
prost-types = "0.11.6"
quickwit_elastic_api_generation = { git = "https://github.com/quickwit-oss/elasticsearch-rs", rev = "c157b19" }
rand = "0.8"
rand_distr = "0.4"
rayon = "1"
rdkafka = { version = "0.28", default-features = false, features = [
  "tokio",
  "libz",
  "ssl",
  "cmake-build",
] }
regex = "1.7.1"
reqwest = { version = "0.11", default-features = false, features = [
  "json",
  "rustls-tls",
] }
rusoto_core = { version = "0.48", default-features = false, features = [
  "rustls",
] }
rusoto_kinesis = { version = "0.48", default-features = false, features = [
  "rustls",
] }
rusoto_mock = { version = "0.48", default-features = false, features = [
  "rustls",
] }
rusoto_s3 = { version = "0.48", default-features = false, features = [
  "rustls",
] }
rusoto_sts = { version = "0.48", default-features = false, features = [
  "rustls",
] }
rust-embed = "6.4.2"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_cbor = "0.11"
serde_json = "1.0"
serde_qs = { version = "0.10", features = ["warp"] }
serde_with = "2.2.0"
serde_yaml = "0.9"
serial_test = "0.9.0"
siphasher = "0.3"
sqlx = { version = "0.6", features = [
  "runtime-tokio-rustls",
  "postgres",
  "migrate",
  "time",
] }
tabled = { version = "0.8", features = ["color"] }
tempfile = "3"
termcolor = "1"
thiserror = "1"
thousands = "0.2.0"
tikv-jemalloc-ctl = "0.5"
tikv-jemallocator = "0.5"
time = { version = "0.3.17", features = ["std", "formatting", "macros"] }
tokio = { version = "1.25", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync"] }
tokio-util = { version = "0.7", features = ["full"] }
toml = "0.6.0"
tonic = { version = "0.8.3", features = ["gzip"] }
tonic-build = "0.8.4"
tower = "0.4.13"
tracing = "0.1.37"
tracing-opentelemetry = "0.18.0"
tracing-subscriber = { version = "0.3.16", features = [
  "time",
  "std",
  "env-filter",
] }
typetag = "0.2"
ulid = "1.0"
username = "0.2"
utoipa = { version = "2.4.2", features = ["json"]}
utoipa-swagger-ui = "3.0.2"
uuid = { version = "1.3", features = ["v4", "serde"] }
value = { git = "https://github.com/quickwit-oss/vector", rev = "859fe61" } # vrl-value
vrl = { git = "https://github.com/quickwit-oss/vector", rev = "859fe61" }
vrl-stdlib = { git = "https://github.com/quickwit-oss/vector", rev = "859fe61" }
warp = "0.3"
wiremock = "0.5"

quickwit-actors = { version = "0.4.0", path = "./quickwit-actors" }
quickwit-aws = { version = "0.4.0", path = "./quickwit-aws" }
quickwit-cluster = { version = "0.4.0", path = "./quickwit-cluster" }
quickwit-common = { version = "0.4.0", path = "./quickwit-common" }
quickwit-config = { version = "0.4.0", path = "./quickwit-config" }
quickwit-control-plane = { version = "0.4.0", path = "./quickwit-control-plane" }
quickwit-core = { version = "0.4.0", path = "./quickwit-core" }
quickwit-directories = { version = "0.4.0", path = "./quickwit-directories" }
quickwit-doc-mapper = { version = "0.4.0", path = "./quickwit-doc-mapper" }
quickwit-grpc-clients = { version = "0.4.0", path = "./quickwit-grpc-clients" }
quickwit-indexing = { version = "0.4.0", path = "./quickwit-indexing" }
quickwit-ingest-api = { version = "0.4.0", path = "./quickwit-ingest-api" }
quickwit-jaeger = { version = "0.4.0", path = "./quickwit-jaeger" }
quickwit-janitor = { version = "0.4.0", path = "./quickwit-janitor" }
quickwit-metastore = { version = "0.4.0", path = "./quickwit-metastore" }
quickwit-opentelemetry = { version = "0.4.0", path = "./quickwit-opentelemetry" }
quickwit-proto = { version = "0.4.0", path = "./quickwit-proto" }
quickwit-rest-client = { version = "0.4.0", path = "./quickwit-rest-client" }
quickwit-search = { version = "0.4.0", path = "./quickwit-search" }
quickwit-serve = { version = "0.4.0", path = "./quickwit-serve" }
quickwit-storage = { version = "0.4.0", path = "./quickwit-storage" }
quickwit-telemetry = { version = "0.4.0", path = "./quickwit-telemetry" }

fastfield_codecs = { git = "https://github.com/quickwit-oss/tantivy/", rev = "c9cb3d0" }
tantivy = { git = "https://github.com/quickwit-oss/tantivy/", rev = "c9cb3d0", default-features = false, features = [
  "mmap",
  "lz4-compression",
  "zstd-compression",
  "quickwit",
] }
tantivy-query-grammar = { git = "https://github.com/quickwit-oss/tantivy/", rev = "c9cb3d0" }

# This is actually not used directly the goal is to fix the version
# used by reqwest. 0.8.30 has an unclear license.
encoding_rs = "=0.8.29"

[patch.crates-io]
sasl2-sys = { git = "https://github.com/quickwit-oss/rust-sasl/", rev = "daca921" }
